### ISSUE TITLE
promote_joins() erros

### ISSUE THREAD

**Issue by muriloventuroso** [henriquebastos/django-aggregate-if#13]
Estava recebendo o seguinte erro ao executar uma queryset com annotate:

promote_joins() takes 2 positional arguments but 3 were given

Fiz uma edição na linha 126 do arquivo aggregate_if.py alterando de query.promote_joins(join_list, True) para query.promote_joins(join_list) e a execução funcionou perfeitamente. Estou usando Django 1.7

Fica a dica para verificar esse aspecto.

**Comment by mbertheau** [comment]
There's been no release with support for Django-1.7 yet. You can try to use the django-1.7 branch https://github.com/henriquebastos/django-aggregate-if/tree/django-1.7, which works for me.

**Comment by mazing** [comment]
Are there any plans on a release with support for Django 1.7?

**Comment by henriquebastos** [comment]
The branch `django-1.7` is well evolved. There's 1 failing test blocking the new release.

I didn't had the time to investigate it any further. Any help is very welcome.

If you're on a hurry you can:

```
pip install git+https://github.com/henriquebastos/django-aggregate-if.git@django-1.7
```
