### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by henriquebastos** [henriquebastos/django-aggregate-if#6]

**Comment by henriquebastos** [comment]
Hey @iurisilvio, @martsberger and @champ. I've just released version django-aggregate-if 0.4.

I also added a contributors section to the README. Thank you for you collaboration.

[]'s, HB!

**Comment by iurisilvio** [comment]
:+1:

**Comment by martsberger** [comment]
Thanks, Henrique, this package has been a great help to me.
